### ISSUE TITLE
Transfer to an Organization

### ISSUE THREAD

**Issue by GlenCFL** [atom-exiles/path-of-exile-item-filter#12]
I've been spending time today trying to get continuous integration implemented and have run up against a few problems due to this repository still being under the single user. Most of these tools are designed to work either only for the primary user or for an entire organization. I think it would be best to transfer this repository over to an organization, so I've created the [Atom Exiles](https://github.com/atom-exiles) group and invited @callum-ramage in order to facilitate this.

The steps to accomplish the transition should be:
- unpublish the package from this repository using ```apm unpublish path-of-exile-item-filter```
- transfer the repository over to the new group
- modify the package.json to point to the new repository
- republish the package under the new organization's repository using ```apm publish```

**Comment by callum-ramage** [comment]
I'll get to this as soon as I can. Just had a kid s I've been pretty busy.

**Comment by GlenCFL** [comment]
Congratulations on that. There's no rush here, so no worries.

I'm going to be working on version 2.0 on another branch for quite a while. The first major change for that version is ditching TypeScript, as the support for it within Atom was already less than stellar and has only degraded over the past six months, especially with the development of "atom-typescript" slowing to a crawl. Atom v1.19 left the published version of that package broken for several weeks, which was a pretty clear signal to move away from it.

**Comment by callum-ramage** [comment]
All sorted. I wasn't sure how to publish without updating the version number so we're now 1.1.7

Thanks for the instructions.

Out of curiosity, what's something that couldn't be done when it was solely in my name?

**Comment by GlenCFL** [comment]
[Travis CI](https://travis-ci.org/) in particular only detects repositories from your own Github or repositories from organizations that you're part of (and have given permissions for). DavidDM and AppVeyor don't need permissions at all and work properly if you just point them at the correct repository.

You probably could have just activated Travis CI on the repository yourself, but I think the organization will be better in the long term.
